sudo: required
language: go
services:
- docker
script:
- scripts/build.sh ${TRAVIS_BRANCH} linux
- scripts/build.sh ${TRAVIS_BRANCH} darwin
deploy:
- provider: releases
  api_key:
    secure: YSN5i3LKjV5PewVS/ydHs2dD/qC1fvepsSBxEYvBsA5LN7iiBhmGAeAHoSJYg2Ewt8qsB8yGLlNsZ9EmCwDEpJQGvjoHXCE7YctDgJbm803wbE+ilsiDSVVfYNirW7lZaYmQrlzzODYR4sx/kfYH0vSMe82pathpgvK/geehZ/FAguhmj44BKj2mmHNYZEoSguX8QBLy4CwKditeP2BQawYSvGjTGsz0h9a15ys1X1mr/Hnva5OQSOuQsxzUBw8NdUCSYX7KAebUIIPRU3UUTJvppPTGIIXr1NYbHpxaROAkxNFI0UfPgV1RCXNKBS9XiiYDb1CmJ5ALwewwIu1NtsJG71dxjBLIw6jlhTqCfgoWUS4ShJZBkpvcVXMis9qXS+KyKNDMWdwiIG5fQL6Ir0N5nlpIi2txCz4C2IG5+DrC9raNWwPoVon7LBSa7ZxWsGjqK5IGtqkpb1b2qk1mn3pNJ0IdtPa60y7ldCY0w+uD74V30FILK+lwZbQi0ZGMj2xuKgQ5/zP4KuZTtviHqfVlKW2Jjw/JEQE52NH54TK9d0D/9Wr9kNmNy24P/hukZg2/uoEGIzRterfDpjSU37cW9ydnblBKEyrKnO+MtD+1d7LTNO2vQDjIvZMJONJ3KSg+++Chi3YA4f+XZN63JqusR7rfRA7JByxXK6/KUww=
  file: bin/*
  on:
    tags: true
- provider: script
  script: bash scripts/publish_docker.sh ${TRAVIS_BRANCH} true
  on:
    tags: true
- provider: script
  script: bash scripts/publish_docker.sh ${TRAVIS_BRANCH}
  on:
    branches:
      except:
      - master
env:
  global:
  - secure: jzD5S8qrIG6TdubUDKmF27NdiLMRgAqsD44My6oZwP188zzxm9nSfYwPaAAIdsWiNYlzybwnho9e6/h66p1fPalewxBt56Dh0PXng5ZRz+sYnMqs1TXSEy66E4hjwotfBTpXTZ95EM3ZwbhSsvZlvx1n7lV2s9GVFcNIFbVXd3TicHmQmUV4GJ/uOisR2UKu7x+G0QQCrydVj5lRl6pnxmVouQVaq/HXMEGc7WFoUV4qFtR2B+1D+OcVQQC+PsocblhVEfoZhzy8Se9wguB29l2cQI2Val2rHUOyrEPSJeeP9rUPdNO59kWC7Znpno2ZMviD3DSWTKUQ2bb9jVtQYs5sp6ComT5f91+YNx61a9N4kzrWAS38SwUzRJS6z4mPs+18Jcst0UffLMvi1ltnWkgNtnLqTNV05YW1ZUTbh92RLE/99GqDw5kFvhQ/5DXvtTpwzSFfXNT9itLZFO+S1oPKj7CgRnjrn6DEwP7zmYpzMGwF8y3UnoCPUC72tWgBlcmcXU0hstawUbh8EyPnCot9ejVfQSzRL6bBoNzv/1viZzu9naT6bLzYS3l659KSYPd0EhJtSBbyELvOFRTG07ez7OdLctyY/umX50L6EF1SELQXji3y5qENXXqkwyCxbkoiewyFBD1i3LcE+CHI8uxYdkzJAy8vsNHORHd2HHY=
  - secure: BsotYYoSmJC1lQskkMtUb4Pq+gQI0XiqzUesKSnkDCqfZAcpLZr3sEJwEkxs54A/5MgS7x0Mn8G8sNP6U2Ehl7C+LAM3wqIsYZkqKpvRgQS9uGO6ip2gL8oaTNeXA3CANXq6cyq3AT3RdC9LAzM+DtZa6ARx2AxrhqAteZ5+RhtTSX7bALqaxcjSCLLceWW/mWx4NceCcfQsag3UxIhVmNHIbThVLcCw5P/mu7p6XZqMZtP/OKyah0UyXHQRBN98ygJzHZY0Vax/RybRrc8kafbp4g6b+sPfSbO3PwMkBEo0/c7jZH1SNW34IGtGNheT13AGqVHRm/ykniOoDvGO15gUydFvmgCOwV4K46O4ALT8lHxDi4byydeTXxe3ayeNlxRgcUn0N2BbMrMtiqPdsbeZlBQtzBxRtZYCbTqLRwS35jbPZhppVWCvq4qJbspQUknsfkOX/eis+0oUonLTwmGsxa1T/JqTykra+BRqmd3e727zYUei9Efm1WI193+WujE3iuYYiTCkgE6gRSoewlOO/S88dULXUS94C64fsZfHA9EAZtMwj6chqse4cDoFfrnPsVZkAOqZNRQCBQ6T0C2rvuC5/7e0LjF5f7pVrI9k08xhI25KjZrJibCRR++fNLZyRFZC6KI7Zu1tzXBiVAdo/qO6yegDO7QHb6EamSo=
