apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    component: {{ .Values.ComponentName }}
    app: {{template "name" .}}
spec:
  replicas: {{ .Values.Replicas }}
  template:
    metadata:
      name: {{ template "fullname" . }}
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        component: {{.Values.ComponentName}}
        app: {{template "name" .}}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{.Values.Image}}:{{.Values.ImageTag}}"
        imagePullPolicy: "{{.Values.ImagePullPolicy}}"
        env:
        - name: KUBEVIZ_TOKEN
          value: {{ .Values.ApiKey }}
        - name: KUBEVIZ_S3BUCKET
          value: {{ .Values.S3Bucket }}
        - name: KUBEVIZ_S3KEY
          value: {{ .Values.S3Key }}
        - name: "AWS_ACCESS_KEY_ID"
          value: "{{ .Values.AwsAccessKey }}"
        - name: "AWS_SECRET_ACCESS_KEY"
          value: "{{ .Values.AwsSecretKey }}"
