apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{template "fullname" .}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "50000000"
  labels:
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: {{.Chart.Name}}-{{.Chart.Version | replace "+" "_"}}
    component: {{.Values.Server.ComponentName}}
    app: {{template "name" .}}
spec:
  rules:
  - host: {{.Values.Server.ApiHostname}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{template "fullname" .}}
          servicePort: 80
